[CmdletBinding(SupportsShouldProcess = $true)]
param([string]$BinDirectory)

$ErrorActionPreference = 'Stop'
$launcher = Join-Path $PSScriptRoot 'launcher.mjs'
if (-not (Test-Path -LiteralPath $launcher)) { throw 'launcher.mjs is missing.' }
Get-Command node -CommandType Application -ErrorAction Stop | Out-Null

if (-not $BinDirectory) {
    $ccp = Get-Command ccp -ErrorAction SilentlyContinue | Select-Object -First 1
    $BinDirectory = if ($ccp -and $ccp.Source) {
        Split-Path -Parent $ccp.Source
    } else {
        Join-Path $env:LOCALAPPDATA 'm365-copilot-cowork-proxy\bin'
    }
}
$BinDirectory = [IO.Path]::GetFullPath($BinDirectory)
$psPath = Join-Path $BinDirectory 'mcp.ps1'
$cmdPath = Join-Path $BinDirectory 'mcp.cmd'
foreach ($path in @($psPath, $cmdPath)) {
    if (Test-Path -LiteralPath $path) {
        $existing = Get-Content -Raw -LiteralPath $path
        if ($existing -notmatch 'M365_COWORK_PROXY_LAUNCHER|cowork-anthropic-poc[\\/]launcher\.mjs|mcp -- Claude CLI through') {
            throw "An unrelated mcp launcher already exists: $path"
        }
    }
}

$escapedLauncher = $launcher.Replace("'", "''")
$psTemplate = @'
# M365_COWORK_PROXY_LAUNCHER -- generated by install.ps1
$node = (Get-Command node -CommandType Application -ErrorAction Stop).Source
$launcher = '__LAUNCHER__'
if ($MyInvocation.ExpectingInput) {
    $input | & $node $launcher @args
} else {
    & $node $launcher @args
}
exit $LASTEXITCODE
'@
$psText = $psTemplate.Replace('__LAUNCHER__', $escapedLauncher)
$cmdText = "@echo off`r`nrem M365_COWORK_PROXY_LAUNCHER`r`nsetlocal DisableDelayedExpansion`r`nnode `"$($launcher.Replace('%', '%%'))`" %*`r`nexit /b %errorlevel%`r`n"

if ($PSCmdlet.ShouldProcess($BinDirectory, 'Install the mcp PowerShell and cmd launchers')) {
    New-Item -ItemType Directory -Path $BinDirectory -Force | Out-Null
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [IO.File]::WriteAllText($psPath, $psText, $utf8)
    [IO.File]::WriteAllText($cmdPath, $cmdText, $utf8)
}

$userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
$present = @(($env:Path -split ';') | ForEach-Object {
    [Environment]::ExpandEnvironmentVariables($_).TrimEnd('\')
}) -contains $BinDirectory.TrimEnd('\')
if (-not $present -and $PSCmdlet.ShouldProcess('User PATH', "Add $BinDirectory")) {
    $newPath = if ([string]::IsNullOrWhiteSpace($userPath)) { $BinDirectory } else { $userPath.TrimEnd(';') + ';' + $BinDirectory }
    [Environment]::SetEnvironmentVariable('Path', $newPath, 'User')
    $env:Path += ';' + $BinDirectory
}
Write-Host "[mcp] Launcher directory: $BinDirectory"
Write-Host '[mcp] Next: mcp auth, then mcp doctor.'
